### ISSUE TITLE
Unused variables in l_equals?

### ISSUE THREAD

**Issue by kyzentun** [alis-is/lua-mbed-hash#1]
l_equals contains this code:
```
    if (hex)
    {
        unsigned char *_hash1 = malloc(len1 / 2);
        unsigned char *_hash2 = malloc(len2 / 2);

        from_hex(hash1, _hash1, len1);
        from_hex(hash2, _hash2, len2);

        int cmp = memcmp(hash1, hash2, len1);
        lua_pushboolean(L, cmp == 0);

        free((void *)_hash1);
        free((void *)_hash2);
    }
```

If I understand correctly, this creates two variables to store the raw binary form of each hash. Then converts the hashes to binary and stores them in the new variables.
The memcmp runs on the original hex forms of the hashes, leaving the binary variables unused.
So is this two unused memory allocations, or is there something I'm not seeing?

The allocation and hex conversion would take longer than running memcmp on the hex, so there's no reason to convert to binary first.

**Comment by cryi** [comment]
Hi. Yea you are right. Sorry I did not notice it sooner. Not sure why I did not get notified. 

Anyway patched and updated to mbedtls 3. And thank you! 🙂
